name: 'Kiriban'
description: 'This is a GitHub Actions that will congratulate you when you reach kiriban for your issue or pull
request number.'
author: 'kumackey <kumak1t09e0@gmail.com>'
inputs:
  LOCALE:
    description: 'Locale'
    required: false
    default: 'en'
  USER_DEFINED_KIRIBANS:
    description: 'User-defined kiribans'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - run: |
        if [[ "${{ github.event_name }}" == "issues" ]]; then
          NUMBER=${{ github.event.issue.number }}
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          NUMBER=${{ github.event.number }}
        else
          echo "Unsupported event name: ${{ github.event_name }}"
          exit 1
        fi
        if [[ -n "${{ inputs.USER_DEFINED_KIRIBANS }}" ]]; then
          go run cmd/*.go -t ${{ github.event_name }} -u "${{ inputs.USER_DEFINED_KIRIBANS }}" $NUMBER
        else
          go run cmd/*.go -t ${{ github.event_name }} $NUMBER
        fi
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        LOCALE: ${{ inputs.LOCALE }}
branding:
  icon: 'gift'
  color: 'orange'
