// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

// Pong defines model for Pong.
type Pong struct {
	Ping string `json:"ping"`
}
